import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// [추가] 뷰포트 설정 (주소창 색상 변경)
export const viewport: Viewport = {
  themeColor: "#09090b", // 앱 헤더 색상(zinc-950)과 동일하게 설정
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false, // 모바일에서 더블탭 확대 방지 (앱처럼 보이게)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
